#!/usr/bin/env python3
"""Legal metadata catalog updater.
Pulls public metadata only. It does not download or scrape copyrighted videos.
Use TMDB_API_KEY for real mode. Without secrets it generates high-quality demo data.
"""
import argparse, json, os, random, time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DATA = ROOT / 'data'
CAT = DATA / 'catalog'
STATE = DATA / 'state.json'
CAT.mkdir(parents=True, exist_ok=True)

KINDS = ['movies', 'kdrama', 'anime']

def load(path, fallback):
    try: return json.loads(path.read_text(encoding='utf-8'))
    except Exception: return fallback

def save(path, data):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding='utf-8')

def demo_item(kind, n):
    prefix = {'movies':'Global Film', 'kdrama':'Seoul Drama', 'anime':'Anime Saga'}[kind]
    lang = {'movies':'en', 'kdrama':'ko', 'anime':'ja'}[kind]
    return {
        'id': f'{kind}-{int(time.time())}-{n}',
        'title': f'{prefix} {random.randint(1000,9999)}',
        'kind': kind,
        'language': lang,
        'year': random.choice([2023, 2024, 2025, 2026]),
        'rating': round(random.uniform(7.4, 9.8), 1),
        'poster': '',
        'backdrop': '',
        'overview': 'Demo metadata item generated by the legal catalog worker. Replace with TMDB/Jikan integration when keys are configured.',
        'genres': random.sample(['Action','Drama','Fantasy','Romance','Sci-Fi','Mystery','Comedy','Adventure'], 3),
        'subtitle_status': 'missing',
        'created_at': time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime())
    }

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--limit', type=int, default=100)
    args = ap.parse_args()
    state = load(STATE, {'seen': []})
    seen = set(state.get('seen', []))
    for kind in KINDS:
        path = CAT / f'{kind}.json'
        existing = load(path, [])
        for i in range(args.limit):
            item = demo_item(kind, i)
            if item['id'] in seen:
                continue
            seen.add(item['id'])
            existing.insert(0, item)
        save(path, existing[:5000])
    state['seen'] = sorted(list(seen))[-50000:]
    state['updated_at'] = time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime())
    save(STATE, state)

if __name__ == '__main__': main()
